services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - db
    networks:
      - appnet

  webserver:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - appnet

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mall_gran_via
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 78801636Ab
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - appnet

  python_api:
    build:
      context: ./python_service
    volumes:
      - ./python_service:/app
    environment:
      DATABASE_URL: postgresql://postgres:78801636Ab@db:5432/mall_gran_via
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  pgdata: